server:
  port: 8080
worker:
  scheme: http
  host: localhost
  port: 8081
logging:
  level:
    com.octo.elab: INFO

---
spring:
    profiles: heroku
server:
  port: ${PORT}
worker:
  scheme: https
  host: ${WORKER_HOST}
  port: 443
